# Generated by Django 2.2.3 on 2019-11-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='music_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracks.Track'),
        ),
    ]
